services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: RizctJ7
      MARIADB_DATABASE: libris_db
      MARIADB_USER: libris_user
      MARIADB_PASSWORD: 8486
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
      image: docker.elastic.co/kibana/kibana:8.18.1
      container_name: kibana
      depends_on:
        - elasticsearch
      environment:
        SERVER_NAME: kibana
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        XPACK_SECURITY_ENABLED: "false"
      ports:
        - "5601:5601"

volumes:
  mariadb_data:
  elasticsearch-data: